DRIVERS-2221 Fix AWS scripts relying on multi-authentication
mongodb-labs/drivers-evergreen-tools pull request #190
Opened 2022-03-02 20:29 UTC by benjirewis

[DRIVERS-2221](https://jira.mongodb.org/browse/DRIVERS-2221)

[SERVER-57369](https://jira.mongodb.org/browse/SERVER-57369) recently removed support for auth as multiple, simultaneous users. Updates our AWS scripts to logout before running authentication functions (as the server did with [this commit](https://github.com/10gen/mongo-enterprise-modules/commit/536a2e918d6fae3334b0ca6cb3d789914db73164)).

2022-03-02 20:46 UTC, ShaneHarvey requested changes
Testing here: https://spruce.mongodb.com/version/621fca2b2fbabe6464f89a5a

2022-03-02 20:46 UTC, ShaneHarvey commented on .evergreen/auth_aws/aws_e2e_assume_role.js
> +const testConn = new Mongo(Mongo().host);
`new Mongo(Mongo().host);` -> `new Mongo();`

Same for the other files.

2022-03-02 23:19 UTC, ShaneHarvey requested changes
Testing again here: https://spruce.mongodb.com/version/621ff9663066155458adfa14

2022-03-02 23:19 UTC, ShaneHarvey commented on .evergreen/auth_aws/lib/ecs_hosted_test.js
>  assert.eq(smoke, 0, "Could not auth with smoke user");
Can you change "Could not auth with smoke user" to "driver .evergreen/run-mongodb-aws-ecs-test.sh script failed"?

2022-03-03 18:11 UTC, ShaneHarvey approved these changes

2022-03-03 18:49 UTC, nbbeeken commented
https://spruce.mongodb.com/version/62210da561837d4d40813afd/tasks

2022-03-03 19:02 UTC, nbbeeken approved these changes

2022-03-03 20:29 UTC, merged