DRIVERS-2416 Add docs and tests for azure oidc
mongodb-labs/drivers-evergreen-tools pull request #376
Opened 2023-11-30 14:20 UTC by blink1073

Tested with https://github.com/mongodb/mongo-python-driver/pull/1443 

- [x] Passing build in Python PR
	`======================== 15 passed, 21 skipped in 3.69s ========================`
- [x] Adjust EVG tasks so OIDC is grouped and Docker test is a new top level test
- [x] Update Azure setup wiki and update link in readme
- [x] Set up VMs to automatically shut down as a failsafe
- [x] See if we can have a default client id on the VM and if so, add a test for it - no, client_id is [required](https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/how-to-use-vm-token#get-a-token-using-http) when there is more than on managed id.

2023-11-30 15:47 UTC, blink1073 commented
evergreen retry

2023-11-30 15:51 UTC, blink1073 commented
@matthewdale I plan to update the top level `auth_oidc` readme in a subsequent PR.

2023-12-01 01:30 UTC, blink1073 commented
evergreen retry

2023-12-14 15:12 UTC, durran requested changes

2023-12-14 15:33 UTC, blink1073 commented on .evergreen/auth_oidc/azure/README.md
> +MONGODB_URI="${MONGODB_URI},TOKEN_AUDIENCE:api%3A%2F%2F${AZUREOIDC_CLIENTID}"
There are two different clients though, so in the Python tests we add them as MongoClient options.

2023-12-14 15:35 UTC, blink1073 commented on .evergreen/auth_oidc/azure/README.md
> +MONGODB_URI="${MONGODB_URI},TOKEN_AUDIENCE:api%3A%2F%2F${AZUREOIDC_CLIENTID}"
Added a note.

2023-12-14 17:58 UTC, durran commented on .evergreen/auth_oidc/azure/README.md
> +MONGODB_URI="${MONGODB_URI},TOKEN_AUDIENCE:api%3A%2F%2F${AZUREOIDC_CLIENTID}"
Thanks.

2023-12-14 17:58 UTC, durran approved these changes

2023-12-14 18:19 UTC, merged