DRIVERS-2882 Add GKE OIDC Support
mongodb-labs/drivers-evergreen-tools pull request #454
Opened 2024-07-02 17:45 UTC by blink1073

2024-07-02 17:47 UTC, blink1073 commented on .evergreen/csfle/gcpkms/create-and-setup-instance.sh
> -# Write the keyfile content to a local JSON path.
This moved to the new login.sh file.

2024-07-02 18:02 UTC, NoahStapp requested changes

2024-07-02 18:34 UTC, NoahStapp approved these changes

2024-07-08 20:23 UTC, NoahStapp approved these changes

2024-07-09 00:42 UTC, merged